In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE

In [2]:
!unzip Amexpert.zip

Archive:  Amexpert.zip
  inflating: sample_submission.csv
  inflating: test.csv
  inflating: train.csv

In [3]:
import os
os.listdir()

['.config',
 'Amexpert.zip',
 'train.csv',
 'sample_submission.csv',
 'test.csv',
 'sample_data']

In [4]:
import pandas as pd

df = pd.read_csv("train.csv")
df.head()

,customer_id,name,age,gender,owns_car,owns_house,no_of_children,net_yearly_income,no_of_days_employed,occupation_type,total_family_members,migrant_worker,yearly_debt_payments,credit_limit,credit_limit_used(%),credit_score,prev_defaults,default_in_last_6months,credit_card_default
0,CST_115179,ita Bose,46,F,N,Y,0.0,107934.04,612.0,Unknown,1.0,1.0,33070.28,18690.93,73,544.0,2,1,1
1,CST_121920,Alper Jonathan,29,M,N,Y,0.0,109862.62,2771.0,Laborers,2.0,0.0,15329.53,37745.19,52,857.0,0,0,0
2,CST_109330,Umesh Desai,37,M,N,Y,0.0,230153.17,204.0,Laborers,2.0,0.0,48416.60,41598.36,43,650.0,0,0,0
3,CST_128288,Rie,39,F,N,Y,0.0,122325.82,11941.0,Core staff,2.0,0.0,22574.36,32627.76,20,754.0,0,0,0
4,CST_151355,McCool,46,M,Y,Y,0.0,387286.00,1459.0,Core staff,1.0,0.0,38282.95,52950.64,75,927.0,0,0,0

In [8]:
df = pd.read_csv("train.csv")

In [9]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45528 entries, 0 to 45527
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              45528 non-null  object
 1   name                     45528 non-null  object
 2   age                      45528 non-null  int64
 3   gender                   45528 non-null  object
 4   owns_car                 44981 non-null  object
 5   owns_house               45528 non-null  object
 6   no_of_children           44754 non-null  float64
 7   net_yearly_income        45528 non-null  float64
 8   no_of_days_employed      45065 non-null  float64
 9   occupation_type          45528 non-null  object
 10  total_family_members     45445 non-null  float64
 11  migrant_worker           45441 non-null  float64
 12  yearly_debt_payments     45433 non-null  float64
 13  credit_limit             45528 non-null  float64
 14  credit_limit_used(%)     45528 non-null  int64
 15  credit_score             45520 non-null  float64
 16  prev_defaults            45528 non-null  int64
 17  default_in_last_6months  45528 non-null  int64
 18  credit_card_default      45528 non-null  int64
dtypes: float64(8), int64(5), object(6)
memory usage: 6.6+ MB

,age,no_of_children,net_yearly_income,no_of_days_employed,total_family_members,migrant_worker,yearly_debt_payments,credit_limit,credit_limit_used(%),credit_score,prev_defaults,default_in_last_6months,credit_card_default
count,45528.000000,44754.000000,4.552800e+04,45065.000000,45445.000000,45441.000000,45433.000000,4.552800e+04,45528.00000,45520.000000,45528.000000,45528.000000,45528.000000
mean,38.993411,0.420655,2.006556e+05,67609.289293,2.158081,0.179111,31796.965311,4.354842e+04,52.23502,782.791257,0.060710,0.050540,0.081203
std,9.543990,0.724097,6.690740e+05,139323.524434,0.911572,0.383450,17269.727234,1.487847e+05,29.37691,100.619746,0.264629,0.219059,0.273149
min,23.000000,0.000000,2.717061e+04,2.000000,1.000000,0.000000,2237.470000,4.003140e+03,0.00000,500.000000,0.000000,0.000000,0.000000
25%,31.000000,0.000000,1.263458e+05,936.000000,2.000000,0.000000,19231.140000,2.397381e+04,27.00000,704.000000,0.000000,0.000000,0.000000
50%,39.000000,0.000000,1.717149e+05,2224.000000,2.000000,0.000000,29081.650000,3.568804e+04,54.00000,786.000000,0.000000,0.000000,0.000000
75%,47.000000,1.000000,2.406038e+05,5817.000000,3.000000,0.000000,40561.150000,5.343576e+04,78.00000,867.000000,0.000000,0.000000,0.000000
max,55.000000,9.000000,1.407590e+08,365252.000000,10.000000,1.000000,328112.860000,3.112997e+07,99.00000,949.000000,2.000000,1.000000,1.000000

In [10]:
df["credit_card_default"].value_counts(normalize=True)

credit_card_default
0    0.918797
1    0.081203
Name: proportion, dtype: float64

In [11]:
df.drop(columns=["customer_id", "name"], inplace=True)

df["gender"] = df["gender"].replace("XNA", "M")

In [12]:
# Categorical → Mode
cat_cols = df.select_dtypes(include="object").columns
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

# Numerical → Median
num_cols = df.select_dtypes(exclude="object").columns
for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

/tmp/ipykernel_13147/2329312119.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipykernel_13147/2329312119.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [13]:
df["credit_utilization"] = df["credit_limit_used(%)"] / 100
df["debt_to_income"] = df["yearly_debt_payments"] / df["net_yearly_income"]
df["income_per_family"] = df["net_yearly_income"] / df["total_family_members"]

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [15]:
from sklearn.model_selection import train_test_split

X = df.drop("credit_card_default", axis=1)
y = df["credit_card_default"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [16]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)

In [17]:
from xgboost import XGBClassifier

model = XGBClassifier(eval_metric="logloss")
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [18]:
from sklearn.metrics import accuracy_score, roc_auc_score

preds = model.predict(X_test)
probs = model.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, preds))
print("AUC:", roc_auc_score(y_test, probs))

Accuracy: 0.9748517461014715
AUC: 0.995108530144441

In [19]:
from sklearn.model_selection import GridSearchCV

params = {
    "max_depth": [3, 5],
    "learning_rate": [0.01, 0.1],
    "n_estimators": [100, 200]
}

grid = GridSearchCV(XGBClassifier(), params, cv=3, scoring="roc_auc")
grid.fit(X_train, y_train)

model = grid.best_estimator_

In [20]:
model = grid.best_estimator_

In [21]:
preds = model.predict(X_test)
probs = model.predict_proba(X_test)[:, 1]

print("Tuned Accuracy:", accuracy_score(y_test, preds))
print("Tuned AUC:", roc_auc_score(y_test, probs))

Tuned Accuracy: 0.973424115967494
Tuned AUC: 0.9948505736418914

In [22]:
train_probs = model.predict_proba(X_train)[:, 1]
test_probs = model.predict_proba(X_test)[:, 1]

print("Train AUC:", roc_auc_score(y_train, train_probs))
print("Test AUC:", roc_auc_score(y_test, test_probs))

Train AUC: 0.9998245493789136
Test AUC: 0.9948505736418914

In [23]:
import pandas as pd

importance = pd.DataFrame({
    "feature": X.columns,
    "importance": model.feature_importances_
}).sort_values(by="importance", ascending=False)

print(importance.head(10))

                 feature  importance
13          credit_score    0.725856
12  credit_limit_used(%)    0.135416
2               owns_car    0.028493
9         migrant_worker    0.026093
16    credit_utilization    0.015416
3             owns_house    0.014853
7        occupation_type    0.008909
4         no_of_children    0.008007
14         prev_defaults    0.005263
10  yearly_debt_payments    0.004118

In [24]:
def risk_category(prob):
    if prob < 0.3:
        return "Low Risk"
    elif prob < 0.7:
        return "Medium Risk"
    else:
        return "High Risk"

risk = [risk_category(p) for p in probs]

In [25]:
import pickle
pickle.dump(model, open("model.pkl", "wb"))